ALTER TABLE "Task" ADD COLUMN "runAttemptCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Task" ADD COLUMN "leaseOwner" TEXT;
ALTER TABLE "Task" ADD COLUMN "leaseExpiresAt" DATETIME;
ALTER TABLE "Task" ADD COLUMN "heartbeatAt" DATETIME;
